// <auto-generated />
using System;
using EcoleBusiness.Services.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoleBusiness.Migrations
{
    [DbContext(typeof(EcoleDbContext))]
    partial class EcoleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EcoleBusiness.DataModels.Ecole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ecoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "St Exupéry"
                        });
                });

            modelBuilder.Entity("EcoleBusiness.DataModels.Fonction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fonctions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Libelle = "Secretaire",
                            Service = "Administration"
                        },
                        new
                        {
                            Id = 2,
                            Libelle = "Educateur",
                            Service = "Equipe pedagogique"
                        },
                        new
                        {
                            Id = 3,
                            Libelle = "Directeur",
                            Service = "Administration"
                        },
                        new
                        {
                            Id = 4,
                            Libelle = "CPE",
                            Service = "Equipe pedagogique"
                        });
                });

            modelBuilder.Entity("EcoleBusiness.DataModels.Matiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Coefficient")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Matieres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Coefficient = 8,
                            Libelle = "Mathematique"
                        },
                        new
                        {
                            Id = 2,
                            Coefficient = 9,
                            Libelle = "Francais"
                        },
                        new
                        {
                            Id = 3,
                            Coefficient = 2,
                            Libelle = "Sport"
                        },
                        new
                        {
                            Id = 4,
                            Coefficient = 7,
                            Libelle = "Science"
                        });
                });

            modelBuilder.Entity("EcoleBusiness.DataModels.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<int>("EcoleId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EcoleId");

                    b.ToTable("Personne");
                });

            modelBuilder.Entity("EcoleBusiness.DataModels.Administratif", b =>
                {
                    b.HasBaseType("EcoleBusiness.DataModels.Personne");

                    b.Property<int?>("FonctionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salaire")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("FonctionId");

                    b.ToTable("Administratifs");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            DateNaissance = new DateTime(1989, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EcoleId = 1,
                            Nom = "Sion",
                            Prenom = "Eva",
                            FonctionId = 3,
                            Salaire = 0m
                        });
                });

            modelBuilder.Entity("EcoleBusiness.DataModels.Eleve", b =>
                {
                    b.HasBaseType("EcoleBusiness.DataModels.Personne");

                    b.Property<int>("Moyenne")
                        .HasColumnType("int");

                    b.HasIndex("Nom", "Prenom");

                    b.ToTable("Eleves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateNaissance = new DateTime(2012, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EcoleId = 1,
                            Nom = "Oumal",
                            Prenom = "Fabien",
                            Moyenne = 12
                        },
                        new
                        {
                            Id = 2,
                            DateNaissance = new DateTime(2009, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EcoleId = 1,
                            Nom = "DePoheur",
                            Prenom = "Agathe",
                            Moyenne = 15
                        });
                });

            modelBuilder.Entity("EcoleBusiness.DataModels.Professeur", b =>
                {
                    b.HasBaseType("EcoleBusiness.DataModels.Personne");

                    b.Property<int>("MatiereId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salaire")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("MatiereId");

                    b.ToTable("Professeurs");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            DateNaissance = new DateTime(1984, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EcoleId = 1,
                            Nom = "Erie",
                            Prenom = "Yann",
                            MatiereId = 4,
                            Salaire = 0m
                        },
                        new
                        {
                            Id = 4,
                            DateNaissance = new DateTime(1978, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EcoleId = 1,
                            Nom = "Mobil",
                            Prenom = "Otto",
                            MatiereId = 3,
                            Salaire = 0m
                        });
                });

            modelBuilder.Entity("EcoleBusiness.DataModels.Personne", b =>
                {
                    b.HasOne("EcoleBusiness.DataModels.Ecole", "Ecole")
                        .WithMany("Personnes")
                        .HasForeignKey("EcoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ecole");
                });

            modelBuilder.Entity("EcoleBusiness.DataModels.Administratif", b =>
                {
                    b.HasOne("EcoleBusiness.DataModels.Fonction", "Fonction")
                        .WithMany()
                        .HasForeignKey("FonctionId");

                    b.HasOne("EcoleBusiness.DataModels.Personne", null)
                        .WithOne()
                        .HasForeignKey("EcoleBusiness.DataModels.Administratif", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Fonction");
                });

            modelBuilder.Entity("EcoleBusiness.DataModels.Eleve", b =>
                {
                    b.HasOne("EcoleBusiness.DataModels.Personne", null)
                        .WithOne()
                        .HasForeignKey("EcoleBusiness.DataModels.Eleve", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoleBusiness.DataModels.Professeur", b =>
                {
                    b.HasOne("EcoleBusiness.DataModels.Personne", null)
                        .WithOne()
                        .HasForeignKey("EcoleBusiness.DataModels.Professeur", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EcoleBusiness.DataModels.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("EcoleBusiness.DataModels.Ecole", b =>
                {
                    b.Navigation("Personnes");
                });
#pragma warning restore 612, 618
        }
    }
}
